# Generated by Django 4.0.4 on 2022-05-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('episodes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=30)),
                ('show_name', models.CharField(max_length=255)),
                ('season', models.IntegerField()),
                ('episodes', models.IntegerField()),
            ],
        ),
    ]
